---
    title: "Multiclass_MNIST"
author: "2014-16757 김보창"
date: '2020 11 11'
output: html_document
---
    
    ```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse) #install.packages("tidyverse")
library(gridExtra)
library(e1071)
library(gmodels) #install.packages("gmodels")
library(class)
library(nnet)
```

```{r}
set.seed(123)
train_csv <- read_csv("mnist_data/mnist_train.csv")
test_csv <- read_csv("mnist_data/mnist_test.csv")

data_process <- function(csv, image_shape = c(28, 28)){
    data_num <- dim(csv)[1]
    
    to_matrix <- function(row){
        label <- row[1]
        image_matrix <- matrix(row[2:(image_shape[1]*image_shape[2]+1)], nrow=image_shape[1], ncol=image_shape[2], byrow = TRUE)
        return(list(label,image_matrix))
    }
    
    processed_data = apply(csv, 1, to_matrix)
    
    fst <- function(mem){
        return(mem[[1]])
    }
    
    snd <- function(mem){
        return(mem[[2]])
    }
    
    label_lst = lapply(processed_data, fst)
    matrix_lst = lapply(processed_data, snd)
    
    
    return(list(label_lst, matrix_lst))
}

matrix_to_vector <- function(matrix, byrow = TRUE){
    if(byrow) mat <- t(matrix)
    else mat <- matrix
    return(as.vector(mat)) # sort by row, if by row = TRUE 
    #  1 2 3
    #1 a b c
    #2 d e f   = >  (a, b, c, d, e, f, g, h, i)
    #3 g h i
    #
    #
}

vector_to_matrix <- function(vector, byrow = TRUE, shape = c(28,28)){
    return(matrix(vector, nrow = shape[1], ncol = shape[2], byrow = byrow))
}


flatten_mat_lst_to_datamat <- function(mat_lst){
    #convert matrix list to data matrix.
    #if matrix shape is a x b, and list length is n
    #then return n x (axb) data matrix.
    shape <- dim(mat_lst[[1]])
    
    vec_lst <- lapply(mat_lst, matrix_to_vector)
    data_mat <- do.call(rbind,vec_lst)
    
    #make_colnames <- function(shape){
    #    xnum <- shape[2]
    #    ynum <- shape[1]
    #    xvec <- unlist(map(1:xnum, as.character))
    #    yvec <- unlist(map(1:ynum, as.character))
    #    return(as.vector(apply(as.array(xvec), 1, str_c, "x", yvec)))
    #}
    
    
    #colnames(data_mat) <- make_colnames(shape)
    
    return(data_mat)
}



# data : list of datas, each data has label & matrix
max_pool_data <- function(data, image_shape = c(28, 28), pool_shape = c(2,2), padding_shape = c(0,0))
{
    max_pool <- function(image_matrix, image_shape, pool_shape, padding_shape){
        image_x = image_shape[1]
        image_y = image_shape[2]
        pool_x = pool_shape[1]
        pool_y = pool_shape[2]
        padding_x = padding_shape[1]
        padding_y = padding_shape[2]
        
        mat = image_matrix
        
        #add padding to matrix
        
        dim_x = dim(mat)[2]
        pad_mat_y <- matrix(rep(0, dim_x * padding_y), nrow = padding_y, ncol = dim_x)
        mat = rbind(pad_mat_y, mat, pad_mat_y)
        # y directional padding matrix (vertical)
        
        dim_y = dim(mat)[1]
        pad_mat_x <- matrix(rep(0, dim_y * padding_x), nrow = dim_y, ncol = padding_y)
        # x directional padding matrix (horizontal)
        
        mat = cbind(pad_mat_x, mat, pad_mat_x)
        
        # maxpooling matrix
        
        if(max(dim(t(mat)) %% pool_shape) > 0){
            stop("pooling dimension is not correct!")
        }
        
        dim_x = dim(mat)[2]
        dim_y = dim(mat)[1]
        
        new_x = dim_x/pool_x
        new_y = dim_y/pool_y
        
        id_mat = matrix(1:(new_y*new_x),nrow = new_y ,ncol = new_x)
        
        maxpooling <- function(n){
            id <- n-1
            start_x = pool_x * (id %/% new_y) + 1
            start_y = pool_y * (id %% new_y) + 1
            
            return(max(mat[start_y:(start_y + pool_y - 1),start_x:(start_x + pool_x - 1)]))
        }
        
        new_mat = apply(id_mat, 1:2, maxpooling)
        
        return(new_mat)
    }
    return(lapply(data, max_pool, image_shape, pool_shape, padding_shape))
}

func_pool_data <- function(data, pooling_fn, image_shape = c(28, 28), pool_shape = c(2,2), padding_shape = c(0,0))
{
    fn_pool <- function(image_matrix, image_shape, pool_shape, padding_shape, pooling_fn){
        image_x = image_shape[1]
        image_y = image_shape[2]
        pool_x = pool_shape[1]
        pool_y = pool_shape[2]
        padding_x = padding_shape[1]
        padding_y = padding_shape[2]
        
        mat = image_matrix
        
        #add padding to matrix
        
        dim_x = dim(mat)[2]
        pad_mat_y <- matrix(rep(0, dim_x * padding_y), nrow = padding_y, ncol = dim_x)
        mat = rbind(pad_mat_y, mat, pad_mat_y)
        # y directional padding matrix (vertical)
        
        dim_y = dim(mat)[1]
        pad_mat_x <- matrix(rep(0, dim_y * padding_x), nrow = dim_y, ncol = padding_y)
        # x directional padding matrix (horizontal)
        
        mat = cbind(pad_mat_x, mat, pad_mat_x)
        
        # maxpooling matrix
        
        if(max(dim(t(mat)) %% pool_shape) > 0){
            stop("pooling dimension is not correct!")
        }
        
        dim_x = dim(mat)[2]
        dim_y = dim(mat)[1]
        
        new_x = dim_x/pool_x
        new_y = dim_y/pool_y
        
        id_mat = matrix(1:(new_y*new_x),nrow = new_y ,ncol = new_x)
        
        funcpooling <- function(n){
            id <- n-1
            start_x = pool_x * (id %/% new_y) + 1
            start_y = pool_y * (id %% new_y) + 1
            
            return(pooling_fn(mat[start_y:(start_y + pool_y - 1),start_x:(start_x + pool_x - 1)]))
        }
        
        new_mat = apply(id_mat, 1:2, funcpooling)
        
        return(new_mat)
    }
    return(lapply(data, fn_pool, image_shape, pool_shape, padding_shape, pooling_fn))
}

print_image <- function(image_mat){
    image_shape = dim(image_mat)
    xsize <- image_shape[2]
    ysize <- image_shape[1]
    mat <- t(apply(image_mat, 2, rev))
    image(1:xsize, 1:ysize, mat, col=gray((0:255)/255))
}

print_dataset <- function(image_mat_lst, x = 6, y = 6){
    #randomly choose matrix in mat_lst, and print them
    par(mfcol=c(x,y))
    par(mar=c(0, 0, 3, 0), xaxs='i', yaxs='i')
    
    index = sample(length(image_mat_lst), x * y, replace = FALSE)
    
    for(i in index)
    {
        print_image(image_mat_lst[[i]])
    }
}

print_dataset_datamat <- function(data_mat, x = 6, y = 6, shape = c(28,28)){
    #randomly choose matrix in mat_lst, and print them
    par(mfcol=c(x,y))
    par(mar=c(0, 0, 3, 0), xaxs='i', yaxs='i')
    
    index = sample(dim(data_mat)[1], x * y, replace = FALSE)
    
    for(i in index)
    {
        image_mat <- vector_to_matrix(data_mat[i,], byrow = TRUE, shape = shape)
        print_image(image_mat)
    }
}


print_dataset_except_par <- function(image_mat_lst, x = 6, y = 6){
    #randomly choose matrix in mat_lst, and print them

    index = sample(length(image_mat_lst), x * y, replace = FALSE)
    
    for(i in index)
    {
        print_image(image_mat_lst[[i]])
    }
}


print_dataset_datamat_except_par <- function(data_mat, x = 6, y = 6, shape = c(28,28)){
    #randomly choose matrix in mat_lst, and print them
    
    index = sample(dim(data_mat)[1], x * y, replace = FALSE)
    
    for(i in index)
    {
        image_mat <- vector_to_matrix(data_mat[i,], byrow = TRUE, shape = shape)
        print_image(image_mat)
    }
}

print_dataset_datamat_except_par_get_index <- function(data_mat, index, shape = c(28,28)){
    #randomly choose matrix in mat_lst, and print them
    
    for(i in index)
    {
        image_mat <- vector_to_matrix(data_mat[i,], byrow = TRUE, shape = shape)
        print_image(image_mat)
    }
}



mean_of_mat_lst <- function(mat_lst){
    # get mean of matrixs, by member by member
    return(apply(simplify2array(mat_lst), 1:2, mean))
}

sd_of_mat_lst <- function(mat_lst){
    # get sd of matrixs, by member by member
    return(apply(simplify2array(mat_lst), 1:2, sd))
}

var_of_mat_lst <- function(mat_lst){
    return(apply(simplify2array(mat_lst), 1:2, var))
}

func_of_mat_lst <- function(mat_lst, func){
    # # apply function to matrix, by member by member
    return(apply(simplify2array(mat_lst), 1:2, func))
}



PCA_mat_lst <- function(mat_lst, usecov = TRUE){
    # get matrix list, and return Principal component result
    # if usecov is True, using cov matrix, else using corr matrix.
    # return PC scores, PC loadings, colmean (to recover by pc), max index of used eigenvalue for pca, eigen decompose result 
    data_mat <- flatten_mat_lst_to_datamat(mat_lst)
    colmean <- colMeans(data_mat)
    mat_dim <- length(colmean)
    data_mat <- sweep(data_mat, 2, colmean) #centerized
    
    if(usecov) eigen_mat <- cov(data_mat)
    else eigen_mat <- cor(data_mat)
    
    eigen_res <- eigen(eigen_mat)
    eigen_vectors <- eigen_res$vectors
    eigen_values <- eigen_res$values
    
    eigen_lst <- cumsum(eigen_values)/sum(eigen_values)
    idx = which(eigen_lst > 0.9)[[1]] # get first index where eigenvalue sum is 90% of total sum
    
    pc_loadings <- eigen_vectors[,1:idx] #pc loading vectors matrix
    pc_scores <- data_mat %*% pc_loadings #pc scores matrix
    
    return(list(pc_scores, pc_loadings, colmean, idx, eigen_res))
}

PCA_mat_lst_using_prev_pca <- function(mat_lst, prev_pca_res){
    # get matrix list, prev pca result and return Principal component result
    data_mat <- flatten_mat_lst_to_datamat(mat_lst)
    colmean <- prev_pca_res[[3]]
    mat_dim <- length(colmean)
    idx <- prev_pca_res[[4]]
    eigen_res <- prev_pca_res[[5]]
    
    data_mat <- sweep(data_mat, 2, colmean) #centerized
    
    pc_loadings <- prev_pca_res[[2]]
    pc_scores <- data_mat %*% pc_loadings
    
    return(list(pc_scores, pc_loadings, colmean, idx, eigen_res))
}


recover_from_pca <- function(PCA_res){
    # get input from pca_result, return recovered data matrix 
    return(sweep(PCA_res[[1]] %*% t(PCA_res[[2]]), 2, -PCA_res[[3]]))
}


multiclass_analysis <- function(train_data_mat, test_data_mat, train_true_label, test_true_label, classify_func, model_name = "pure")
    # predict true label, and analysis result (ex : accuracy)
    # get train/test data, and classify function.
    # classify function's input is train/test matrix
    #                     output is predicted label of test matrix (using train matrix's model)
{
    train_df <- data.frame("label" = train_true_label, "data" = train_data_mat)
    train_df$label <- as.factor(train_df$label)
    
    test_df <- data.frame("label" = test_true_label, "data" = test_data_mat)
    test_df$label <- as.factor(test_df$label)
    classify_res <- classify_func(train_df, test_df, model_name)
    train_predicted_label <- classify_res[[1]]
    test_predicted_label <- classify_res[[2]]
    
    res <- classify_res == as.factor(test_true_label)
    
    accuracy <- sum(res == TRUE)/length(test_true_label)
    
    print(str_c(model_name, "'s accuracy is ", toString(accuracy)))
    return(classify_res)
}

svm_classify_func <- function(train_df, test_df, model_name)
    # train matrix : has label & data's
    # test matrix : has label & data's
{
    filename <- str_c(model_name,"_train_svm.rds")
    train_timename <- str_c(model_name,"_train_svm_train_time.rds")
    predict_timename <- str_c(model_name,"_train_svm_predict_time.rds")
    if(file.exists(filename))
    {
        train_svm <- readRDS(filename)
    }
    else
    {
        print("elpased time when trainning\n")
        train_time <- system.time(
            {train_svm <- svm(label ~ ., data=train_df, 
                     method="C-classification", kernal="radial", cost=1, cachesize = 4096)}
            )
        print(train_time)
        saveRDS(train_svm, filename) # save model to execute other things.
        saveRDS(train_time, train_timename)
    }
    print("elpased time when predicting\n")
    predict_time <- system.time({svm_res <- predict(train_svm, test_df)})
    print(predict_time)
    if(!file.exists(predict_timename)) saveRDS(predict_time, predict_timename)
    return(svm_res)
}

knn_1_classify_func <- function(train_df, test_df, model_name)
    # train matrix : has label & data's
    # test matrix : has label & data's
{
    filename <- str_c(model_name,"_train_knn_1.rds")
    train_timename <- str_c(model_name,"_train_knn_1_train_time.rds")
    predict_timename <- str_c(model_name,"_train_knn_1_predict_time.rds")
    
    print("elpased time when predicting\n")
    predict_time <- system.time({knn_res <- knn(train = train_df[,names(train_df) != "label"], test = test_df[,names(train_df) != "label"], cl = train_df$label, k = 1)})
    print(predict_time)
    if(!file.exists(predict_timename)) saveRDS(predict_time, predict_timename)
    return(knn_res)
}

knn_2_classify_func <- function(train_df, test_df, model_name)
    # train matrix : has label & data's
    # test matrix : has label & data's
{
    filename <- str_c(model_name,"_train_knn_2.rds")
    train_timename <- str_c(model_name,"_train_knn_2_train_time.rds")
    predict_timename <- str_c(model_name,"_train_knn_2_predict_time.rds")
    
    print("elpased time when predicting\n")
    predict_time <- system.time({knn_res <- knn(train = train_df[,names(train_df) != "label"], test = test_df[,names(train_df) != "label"], cl = train_df$label, k = 2)})
    print(predict_time)
    if(!file.exists(predict_timename)) saveRDS(predict_time, predict_timename)
    return(knn_res)
}

multinom_classify_func <- function(train_df, test_df, model_name)
    # train matrix : has label & data's
    # test matrix : has label & data's
{
    filename <- str_c(model_name,"_train_multinom.rds")
    train_timename <- str_c(model_name,"_train_multinom_train_time.rds")
    predict_timename <- str_c(model_name,"_train_multinom_predict_time.rds")
    if(file.exists(filename))
    {
        train_multinom <- readRDS(filename)
    }
    else
    {
        print("elpased time when trainning\n")
        train_time <- system.time(
            {train_multinom <- multinom(label ~ ., data=train_df, 
                     maxit = 5000, abstol = 25.0)}
            )
        print(train_time)
        saveRDS(train_multinom, filename) # save model to execute other things.
        saveRDS(train_time, train_timename)
    }
    print("elpased time when predicting\n")
    predict_time <- system.time({multinom_res <- predict(train_multinom, test_df)})
    print(predict_time)
    if(!file.exists(predict_timename)) saveRDS(predict_time, predict_timename)
    return(multinom_res)
}




train_data <- data_process(train_csv)
test_data <- data_process(test_csv)

train_label_lst <- train_data[[1]]
train_mat_lst <- train_data[[2]]
test_label_lst <- test_data[[1]]
test_mat_lst <- test_data[[2]]
train_label <- unname(unlist(train_label_lst))
test_label <- unname(unlist(test_label_lst))


train_mat_lst_maxpooled2x2_filename <- "train_mat_lst_maxpooled2x2.rds"
test_mat_lst_maxpooled2x2_filename <- "test_mat_lst_maxpooled2x2.rds"
train_mat_lst_maxpooled3x3_filename <- "train_mat_lst_maxpooled3x3.rds"
test_mat_lst_maxpooled3x3_filename <- "test_mat_lst_maxpooled3x3.rds"
train_mat_lst_maxpooled4x4_filename <- "train_mat_lst_maxpooled4x4.rds"
test_mat_lst_maxpooled4x4_filename <- "test_mat_lst_maxpooled4x4.rds"
train_mat_lst_meanpooled2x2_filename <- "train_mat_lst_meanpooled2x2.rds"
test_mat_lst_meanpooled2x2_filename <- "test_mat_lst_meanpooled2x2.rds"
train_mat_lst_meanpooled3x3_filename <- "train_mat_lst_meanpooled3x3.rds"
test_mat_lst_meanpooled3x3_filename <- "test_mat_lst_meanpooled3x3.rds"
train_mat_lst_meanpooled4x4_filename <- "train_mat_lst_meanpooled4x4.rds"
test_mat_lst_meanpooled4x4_filename <- "test_mat_lst_meanpooled4x4.rds"

if(!file.exists(train_mat_lst_maxpooled2x2_filename)){
    train_mat_lst_maxpooled2x2 <- max_pool_data(train_mat_lst, image_shape = c(28, 28), pool_shape = c(2,2), padding_shape = c(0,0))
    saveRDS(train_mat_lst_maxpooled2x2, train_mat_lst_maxpooled2x2_filename)
}else{
    train_mat_lst_maxpooled2x2 <- readRDS(train_mat_lst_maxpooled2x2_filename)
}

if(!file.exists(test_mat_lst_maxpooled2x2_filename)){
    test_mat_lst_maxpooled2x2 <- max_pool_data(test_mat_lst, image_shape = c(28, 28), pool_shape = c(2,2), padding_shape = c(0,0))
    saveRDS(test_mat_lst_maxpooled2x2, test_mat_lst_maxpooled2x2_filename)
}else{
    test_mat_lst_maxpooled2x2 <- readRDS(test_mat_lst_maxpooled2x2_filename)
}

if(!file.exists(train_mat_lst_maxpooled3x3_filename)){
    train_mat_lst_maxpooled3x3 <- max_pool_data(train_mat_lst, image_shape = c(28, 28), pool_shape = c(3,3), padding_shape = c(1,1))
    saveRDS(train_mat_lst_maxpooled3x3, train_mat_lst_maxpooled3x3_filename)
}else{
    train_mat_lst_maxpooled3x3 <- readRDS(train_mat_lst_maxpooled3x3_filename)
}

if(!file.exists(test_mat_lst_maxpooled3x3_filename)){
    test_mat_lst_maxpooled3x3 <- max_pool_data(test_mat_lst, image_shape = c(28, 28), pool_shape = c(3,3), padding_shape = c(1,1))
    saveRDS(test_mat_lst_maxpooled3x3, test_mat_lst_maxpooled3x3_filename)
}else{
    test_mat_lst_maxpooled3x3 <- readRDS(test_mat_lst_maxpooled3x3_filename)
}

if(!file.exists(train_mat_lst_maxpooled4x4_filename)){
    train_mat_lst_maxpooled4x4 <- max_pool_data(train_mat_lst, image_shape = c(28, 28), pool_shape = c(4,4), padding_shape = c(0,0))
    saveRDS(train_mat_lst_maxpooled4x4, train_mat_lst_maxpooled4x4_filename)
}else{
    train_mat_lst_maxpooled4x4 <- readRDS(train_mat_lst_maxpooled4x4_filename)
}

if(!file.exists(test_mat_lst_maxpooled4x4_filename)){
    test_mat_lst_maxpooled4x4 <- max_pool_data(test_mat_lst, image_shape = c(28, 28), pool_shape = c(4,4), padding_shape = c(0,0))
    saveRDS(test_mat_lst_maxpooled4x4, test_mat_lst_maxpooled4x4_filename)
}else{
    test_mat_lst_maxpooled4x4 <- readRDS(test_mat_lst_maxpooled4x4_filename)
}


if(!file.exists(train_mat_lst_meanpooled2x2_filename)){
    train_mat_lst_meanpooled2x2 <- func_pool_data(train_mat_lst, mean, image_shape = c(28, 28), pool_shape = c(2,2), padding_shape = c(0,0))
    saveRDS(train_mat_lst_meanpooled2x2, train_mat_lst_meanpooled2x2_filename)
}else{
    train_mat_lst_meanpooled2x2 <- readRDS(train_mat_lst_meanpooled2x2_filename)
}

if(!file.exists(test_mat_lst_meanpooled2x2_filename)){
    test_mat_lst_meanpooled2x2 <- func_pool_data(test_mat_lst, mean, image_shape = c(28, 28), pool_shape = c(2,2), padding_shape = c(0,0))
    saveRDS(test_mat_lst_meanpooled2x2, test_mat_lst_meanpooled2x2_filename)
}else{
    test_mat_lst_meanpooled2x2 <- readRDS(test_mat_lst_meanpooled2x2_filename)
}

if(!file.exists(train_mat_lst_meanpooled3x3_filename)){
    train_mat_lst_meanpooled3x3 <- func_pool_data(train_mat_lst, mean, image_shape = c(28, 28), pool_shape = c(3,3), padding_shape = c(1,1))
    saveRDS(train_mat_lst_meanpooled3x3, train_mat_lst_meanpooled3x3_filename)
}else{
    train_mat_lst_meanpooled3x3 <- readRDS(train_mat_lst_meanpooled3x3_filename)
}

if(!file.exists(test_mat_lst_meanpooled3x3_filename)){
    test_mat_lst_meanpooled3x3 <- func_pool_data(test_mat_lst, mean, image_shape = c(28, 28), pool_shape = c(3,3), padding_shape = c(1,1))
    saveRDS(test_mat_lst_meanpooled3x3, test_mat_lst_meanpooled3x3_filename)
}else{
    test_mat_lst_meanpooled3x3 <- readRDS(test_mat_lst_meanpooled3x3_filename)
}

if(!file.exists(train_mat_lst_meanpooled4x4_filename)){
    train_mat_lst_meanpooled4x4 <- func_pool_data(train_mat_lst, mean, image_shape = c(28, 28), pool_shape = c(4,4), padding_shape = c(0,0))
    saveRDS(train_mat_lst_meanpooled4x4, train_mat_lst_meanpooled4x4_filename)
}else{
    train_mat_lst_meanpooled4x4 <- readRDS(train_mat_lst_meanpooled4x4_filename)
}

if(!file.exists(test_mat_lst_meanpooled4x4_filename)){
    test_mat_lst_meanpooled4x4 <- func_pool_data(test_mat_lst, mean, image_shape = c(28, 28), pool_shape = c(4,4), padding_shape = c(0,0))
    saveRDS(test_mat_lst_meanpooled4x4, test_mat_lst_meanpooled4x4_filename)
}else{
    test_mat_lst_meanpooled4x4 <- readRDS(test_mat_lst_meanpooled4x4_filename)
}

data_mat_train_mat_lst <- flatten_mat_lst_to_datamat(train_mat_lst)
data_mat_test_mat_lst <- flatten_mat_lst_to_datamat(test_mat_lst)
data_mat_train_mat_lst_maxpooled2x2 <- flatten_mat_lst_to_datamat(train_mat_lst_maxpooled2x2)
data_mat_train_mat_lst_maxpooled3x3 <- flatten_mat_lst_to_datamat(train_mat_lst_maxpooled3x3)
data_mat_train_mat_lst_maxpooled4x4 <- flatten_mat_lst_to_datamat(train_mat_lst_maxpooled4x4)
data_mat_test_mat_lst_maxpooled2x2 <- flatten_mat_lst_to_datamat(test_mat_lst_maxpooled2x2)
data_mat_test_mat_lst_maxpooled3x3 <- flatten_mat_lst_to_datamat(test_mat_lst_maxpooled3x3)
data_mat_test_mat_lst_maxpooled4x4 <- flatten_mat_lst_to_datamat(test_mat_lst_maxpooled4x4)
data_mat_train_mat_lst_meanpooled2x2 <- flatten_mat_lst_to_datamat(train_mat_lst_meanpooled2x2)
data_mat_train_mat_lst_meanpooled3x3 <- flatten_mat_lst_to_datamat(train_mat_lst_meanpooled3x3)
data_mat_train_mat_lst_meanpooled4x4 <- flatten_mat_lst_to_datamat(train_mat_lst_meanpooled4x4)
data_mat_test_mat_lst_meanpooled2x2 <- flatten_mat_lst_to_datamat(test_mat_lst_meanpooled2x2)
data_mat_test_mat_lst_meanpooled3x3 <- flatten_mat_lst_to_datamat(test_mat_lst_meanpooled3x3)
data_mat_test_mat_lst_meanpooled4x4 <- flatten_mat_lst_to_datamat(test_mat_lst_meanpooled4x4)

PCA_res_train_mat_lst <- PCA_mat_lst(train_mat_lst)
data_mat_recovered_train_mat_lst <- recover_from_pca(PCA_res_train_mat_lst)
print_dataset_datamat(data_mat_recovered_train_mat_lst, x=5, y=5, shape = dim(train_mat_lst[[1]]))

PCA_res_test_mat_lst <- PCA_mat_lst_using_prev_pca(test_mat_lst, PCA_res_train_mat_lst) 
data_mat_recovered_test_mat_lst <- recover_from_pca(PCA_res_test_mat_lst)
print_dataset_datamat(data_mat_recovered_test_mat_lst, x=5, y=5, shape = dim(test_mat_lst[[1]]))

PCA_res_train_mat_lst_maxpooled2x2 <- PCA_mat_lst(train_mat_lst_maxpooled2x2)
data_mat_recovered_train_mat_lst_maxpooled2x2 <- recover_from_pca(PCA_res_train_mat_lst_maxpooled2x2)
print_dataset_datamat(data_mat_recovered_train_mat_lst_maxpooled2x2, x=5, y=5, shape = dim(train_mat_lst_maxpooled2x2[[1]]))

PCA_res_test_mat_lst_maxpooled2x2 <- PCA_mat_lst_using_prev_pca(test_mat_lst_maxpooled2x2, PCA_res_train_mat_lst_maxpooled2x2) 
data_mat_recovered_test_mat_lst_maxpooled2x2 <- recover_from_pca( PCA_res_test_mat_lst_maxpooled2x2)
print_dataset_datamat(data_mat_recovered_test_mat_lst_maxpooled2x2, x=5, y=5, shape = dim(test_mat_lst_maxpooled2x2[[1]]))

PCA_res_train_mat_lst_maxpooled3x3 <- PCA_mat_lst(train_mat_lst_maxpooled3x3)
data_mat_recovered_train_mat_lst_maxpooled3x3 <- recover_from_pca(PCA_res_train_mat_lst_maxpooled3x3)
print_dataset_datamat(data_mat_recovered_train_mat_lst_maxpooled3x3, x=5, y=5, shape = dim(train_mat_lst_maxpooled3x3[[1]]))

PCA_res_test_mat_lst_maxpooled3x3 <- PCA_mat_lst_using_prev_pca(test_mat_lst_maxpooled3x3, PCA_res_train_mat_lst_maxpooled3x3) 
data_mat_recovered_test_mat_lst_maxpooled3x3 <- recover_from_pca(PCA_res_test_mat_lst_maxpooled3x3)
print_dataset_datamat(data_mat_recovered_test_mat_lst_maxpooled3x3, x=5, y=5, shape = dim(test_mat_lst_maxpooled3x3[[1]]))

PCA_res_train_mat_lst_maxpooled4x4 <- PCA_mat_lst(train_mat_lst_maxpooled4x4)
data_mat_recovered_train_mat_lst_maxpooled4x4 <- recover_from_pca(PCA_res_train_mat_lst_maxpooled4x4)
print_dataset_datamat(data_mat_recovered_train_mat_lst_maxpooled4x4, x=5, y=5, shape = dim(train_mat_lst_maxpooled4x4[[1]]))

PCA_res_test_mat_lst_maxpooled4x4 <- PCA_mat_lst_using_prev_pca(test_mat_lst_maxpooled4x4, PCA_res_train_mat_lst_maxpooled4x4) 
data_mat_recovered_test_mat_lst_maxpooled4x4 <- recover_from_pca(PCA_res_test_mat_lst_maxpooled4x4)
print_dataset_datamat(data_mat_recovered_test_mat_lst_maxpooled4x4, x=5, y=5, shape = dim(test_mat_lst_maxpooled4x4[[1]]))

PCA_res_train_mat_lst_meanpooled2x2 <- PCA_mat_lst(train_mat_lst_meanpooled2x2)
data_mat_recovered_train_mat_lst_meanpooled2x2 <- recover_from_pca(PCA_res_train_mat_lst_meanpooled2x2)
print_dataset_datamat(data_mat_recovered_train_mat_lst_meanpooled2x2, x=5, y=5, shape = dim(train_mat_lst_meanpooled2x2[[1]]))

PCA_res_test_mat_lst_meanpooled2x2 <- PCA_mat_lst_using_prev_pca(test_mat_lst_meanpooled2x2, PCA_res_train_mat_lst_meanpooled2x2) 
data_mat_recovered_test_mat_lst_meanpooled2x2 <- recover_from_pca( PCA_res_test_mat_lst_meanpooled2x2)
print_dataset_datamat(data_mat_recovered_test_mat_lst_meanpooled2x2, x=5, y=5, shape = dim(test_mat_lst_meanpooled2x2[[1]]))

PCA_res_train_mat_lst_meanpooled3x3 <- PCA_mat_lst(train_mat_lst_meanpooled3x3)
data_mat_recovered_train_mat_lst_meanpooled3x3 <- recover_from_pca(PCA_res_train_mat_lst_meanpooled3x3)
print_dataset_datamat(data_mat_recovered_train_mat_lst_meanpooled3x3, x=5, y=5, shape = dim(train_mat_lst_meanpooled3x3[[1]]))

PCA_res_test_mat_lst_meanpooled3x3 <- PCA_mat_lst_using_prev_pca(test_mat_lst_meanpooled3x3, PCA_res_train_mat_lst_meanpooled3x3) 
data_mat_recovered_test_mat_lst_meanpooled3x3 <- recover_from_pca(PCA_res_test_mat_lst_meanpooled3x3)
print_dataset_datamat(data_mat_recovered_test_mat_lst_meanpooled3x3, x=5, y=5, shape = dim(test_mat_lst_meanpooled3x3[[1]]))

PCA_res_train_mat_lst_meanpooled4x4 <- PCA_mat_lst(train_mat_lst_meanpooled4x4)
data_mat_recovered_train_mat_lst_meanpooled4x4 <- recover_from_pca(PCA_res_train_mat_lst_meanpooled4x4)
print_dataset_datamat(data_mat_recovered_train_mat_lst_meanpooled4x4, x=5, y=5, shape = dim(train_mat_lst_meanpooled4x4[[1]]))

PCA_res_test_mat_lst_meanpooled4x4 <- PCA_mat_lst_using_prev_pca(test_mat_lst_meanpooled4x4, PCA_res_train_mat_lst_meanpooled4x4) 
data_mat_recovered_test_mat_lst_meanpooled4x4 <- recover_from_pca(PCA_res_test_mat_lst_meanpooled4x4)
print_dataset_datamat(data_mat_recovered_test_mat_lst_meanpooled4x4, x=5, y=5, shape = dim(test_mat_lst_meanpooled4x4[[1]]))



PC_score_train_mat <- PCA_res_train_mat_lst[[1]]
PC_score_test_mat <- PCA_res_test_mat_lst[[1]]
PC_score_train_mat_maxpooled2x2 <- PCA_res_train_mat_lst_maxpooled2x2[[1]]
PC_score_test_mat_maxpooled2x2 <- PCA_res_test_mat_lst_maxpooled2x2[[1]]
PC_score_train_mat_maxpooled3x3 <- PCA_res_train_mat_lst_maxpooled3x3[[1]]
PC_score_test_mat_maxpooled3x3 <- PCA_res_test_mat_lst_maxpooled3x3[[1]]
PC_score_train_mat_maxpooled4x4 <- PCA_res_train_mat_lst_maxpooled4x4[[1]]
PC_score_test_mat_maxpooled4x4 <- PCA_res_test_mat_lst_maxpooled4x4[[1]]
PC_score_train_mat_meanpooled2x2 <- PCA_res_train_mat_lst_meanpooled2x2[[1]]
PC_score_test_mat_meanpooled2x2 <- PCA_res_test_mat_lst_meanpooled2x2[[1]]
PC_score_train_mat_meanpooled3x3 <- PCA_res_train_mat_lst_meanpooled3x3[[1]]
PC_score_test_mat_meanpooled3x3 <- PCA_res_test_mat_lst_meanpooled3x3[[1]]
PC_score_train_mat_meanpooled4x4 <- PCA_res_train_mat_lst_meanpooled4x4[[1]]
PC_score_test_mat_meanpooled4x4 <- PCA_res_test_mat_lst_meanpooled4x4[[1]]


svd_pure_res <- multiclass_analysis(PC_score_train_mat, PC_score_test_mat, train_label, test_label,  svm_classify_func, "pure")
#svd of PCA (raw data)

svd_maxpooled2x2_res <- multiclass_analysis(PC_score_train_mat_maxpooled2x2, PC_score_test_mat_maxpooled2x2, train_label, test_label,  svm_classify_func, "maxpooled2x2")
#svd of PCA (maxpooled2x2)

svd_maxpooled3x3_res <- multiclass_analysis(PC_score_train_mat_maxpooled3x3, PC_score_test_mat_maxpooled3x3, train_label, test_label,  svm_classify_func, "maxpooled3x3")
#svd of PCA (maxpooled3x3)

svd_maxpooled4x4_res <- multiclass_analysis(PC_score_train_mat_maxpooled4x4, PC_score_test_mat_maxpooled4x4, train_label, test_label,  svm_classify_func, "maxpooled4x4")
#svd of PCA (maxpooled4x4)

svd_meanpooled2x2_res <- multiclass_analysis(PC_score_train_mat_meanpooled2x2, PC_score_test_mat_meanpooled2x2, train_label, test_label,  svm_classify_func, "meanpooled2x2")
#svd of PCA (meanpooled2x2)

svd_meanpooled3x3_res <- multiclass_analysis(PC_score_train_mat_meanpooled3x3, PC_score_test_mat_meanpooled3x3, train_label, test_label,  svm_classify_func, "meanpooled3x3")
#svd of PCA (meanpooled3x3)

svd_meanpooled4x4_res <- multiclass_analysis(PC_score_train_mat_meanpooled4x4, PC_score_test_mat_meanpooled4x4, train_label, test_label,  svm_classify_func, "meanpooled4x4")
#svd of PCA (meanpooled4x4)

#multiclass_analysis(data_mat_train_mat_lst, data_mat_test_mat_lst, train_label, test_label,  svm_classify_func, "pure_without_pca")
#svd of raw


knn_1_pure_res <- multiclass_analysis(PC_score_train_mat, PC_score_test_mat, train_label, test_label,  knn_1_classify_func, "pure")
#knn_1 of PCA (raw data)

knn_1_maxpooled2x2_res <- multiclass_analysis(PC_score_train_mat_maxpooled2x2, PC_score_test_mat_maxpooled2x2, train_label, test_label,  knn_1_classify_func, "maxpooled2x2")
#knn_1 of PCA (maxpooled2x2)

knn_1_maxpooled3x3_res <- multiclass_analysis(PC_score_train_mat_maxpooled3x3, PC_score_test_mat_maxpooled3x3, train_label, test_label,  knn_1_classify_func, "maxpooled3x3")
#knn_1 of PCA (maxpooled3x3)

knn_1_maxpooled4x4_res <- multiclass_analysis(PC_score_train_mat_maxpooled4x4, PC_score_test_mat_maxpooled4x4, train_label, test_label,  knn_1_classify_func, "maxpooled4x4")
#knn_1 of PCA (maxpooled4x4)

knn_1_meanpooled2x2_res <- multiclass_analysis(PC_score_train_mat_meanpooled2x2, PC_score_test_mat_meanpooled2x2, train_label, test_label,  knn_1_classify_func, "meanpooled2x2")
#knn_1 of PCA (meanpooled2x2)

knn_1_meanpooled3x3_res <- multiclass_analysis(PC_score_train_mat_meanpooled3x3, PC_score_test_mat_meanpooled3x3, train_label, test_label,  knn_1_classify_func, "meanpooled3x3")
#knn_1 of PCA (meanpooled3x3)

knn_1_meanpooled4x4_res <- multiclass_analysis(PC_score_train_mat_meanpooled4x4, PC_score_test_mat_meanpooled4x4, train_label, test_label,  knn_1_classify_func, "meanpooled4x4")
#knn_1 of PCA (meanpooled4x4)

knn_2_pure_res <- multiclass_analysis(PC_score_train_mat, PC_score_test_mat, train_label, test_label,  knn_2_classify_func, "pure")
#knn_2 of PCA (raw data)

knn_2_maxpooled2x2_res <- multiclass_analysis(PC_score_train_mat_maxpooled2x2, PC_score_test_mat_maxpooled2x2, train_label, test_label,  knn_2_classify_func, "maxpooled2x2")
#knn_2 of PCA (maxpooled2x2)

knn_2_maxpooled3x3_res <- multiclass_analysis(PC_score_train_mat_maxpooled3x3, PC_score_test_mat_maxpooled3x3, train_label, test_label,  knn_2_classify_func, "maxpooled3x3")
#knn_2 of PCA (maxpooled3x3)

knn_2_maxpooled4x4_res <- multiclass_analysis(PC_score_train_mat_maxpooled4x4, PC_score_test_mat_maxpooled4x4, train_label, test_label,  knn_2_classify_func, "maxpooled4x4")
#knn_2 of PCA (maxpooled4x4)

knn_2_meanpooled2x2_res <- multiclass_analysis(PC_score_train_mat_meanpooled2x2, PC_score_test_mat_meanpooled2x2, train_label, test_label,  knn_2_classify_func, "meanpooled2x2")
#knn_2 of PCA (meanpooled2x2)

knn_2_meanpooled3x3_res <- multiclass_analysis(PC_score_train_mat_meanpooled3x3, PC_score_test_mat_meanpooled3x3, train_label, test_label,  knn_2_classify_func, "meanpooled3x3")
#knn_2 of PCA (meanpooled3x3)

knn_2_meanpooled4x4_res <- multiclass_analysis(PC_score_train_mat_meanpooled4x4, PC_score_test_mat_meanpooled4x4, train_label, test_label,  knn_2_classify_func, "meanpooled4x4")
#knn_2 of PCA (meanpooled4x4)

multinom_pure_res <- multiclass_analysis(PC_score_train_mat, PC_score_test_mat, train_label, test_label,  multinom_classify_func, "pure")
#multinom of PCA (raw data)

multinom_maxpooled2x2_res <- multiclass_analysis(PC_score_train_mat_maxpooled2x2, PC_score_test_mat_maxpooled2x2, train_label, test_label,  multinom_classify_func, "maxpooled2x2")
#multinom of PCA (maxpooled2x2)

multinom_maxpooled3x3_res <- multiclass_analysis(PC_score_train_mat_maxpooled3x3, PC_score_test_mat_maxpooled3x3, train_label, test_label,  multinom_classify_func, "maxpooled3x3")
#multinom of PCA (maxpooled3x3)

multinom_maxpooled4x4_res <- multiclass_analysis(PC_score_train_mat_maxpooled4x4, PC_score_test_mat_maxpooled4x4, train_label, test_label,  multinom_classify_func, "maxpooled4x4")
#multinom of PCA (maxpooled4x4)

multinom_meanpooled2x2_res <- multiclass_analysis(PC_score_train_mat_meanpooled2x2, PC_score_test_mat_meanpooled2x2, train_label, test_label,  multinom_classify_func, "meanpooled2x2")
#multinom of PCA (meanpooled2x2)

multinom_meanpooled3x3_res <- multiclass_analysis(PC_score_train_mat_meanpooled3x3, PC_score_test_mat_meanpooled3x3, train_label, test_label,  multinom_classify_func, "meanpooled3x3")
#multinom of PCA (meanpooled3x3)

multinom_meanpooled4x4_res <- multiclass_analysis(PC_score_train_mat_meanpooled4x4, PC_score_test_mat_meanpooled4x4, train_label, test_label,  multinom_classify_func, "meanpooled4x4")
#multinom of PCA (meanpooled4x4)

CrossTable(x = as.factor(test_label), y = svd_pure_res, prop.chisq = FALSE)

CrossTable(x = as.factor(test_label), y = svd_maxpooled2x2_res, prop.chisq = FALSE)

CrossTable(x = as.factor(test_label), y = svd_maxpooled3x3_res, prop.chisq = FALSE)

CrossTable(x = as.factor(test_label), y = svd_maxpooled4x4_res, prop.chisq = FALSE)

CrossTable(x = as.factor(test_label), y = svd_meanpooled2x2_res, prop.chisq = FALSE)

CrossTable(x = as.factor(test_label), y = svd_meanpooled3x3_res, prop.chisq = FALSE)

CrossTable(x = as.factor(test_label), y = svd_meanpooled4x4_res, prop.chisq = FALSE)


par(mfcol=c(5,7))
par(mar=c(0, 0, 3, 0), xaxs='i', yaxs='i')
print_dataset_datamat_except_par_get_index(data_mat_train_mat_lst, 1:5, shape = dim(train_mat_lst[[1]]))
print_dataset_datamat_except_par_get_index(data_mat_train_mat_lst_maxpooled2x2, 1:5, shape = dim(train_mat_lst_maxpooled2x2[[1]]))
print_dataset_datamat_except_par_get_index(data_mat_train_mat_lst_maxpooled3x3, 1:5, shape = dim(train_mat_lst_maxpooled3x3[[1]]))
print_dataset_datamat_except_par_get_index(data_mat_train_mat_lst_maxpooled4x4, 1:5, shape = dim(train_mat_lst_maxpooled4x4[[1]]))
print_dataset_datamat_except_par_get_index(data_mat_train_mat_lst_meanpooled2x2, 1:5, shape = dim(train_mat_lst_meanpooled2x2[[1]]))
print_dataset_datamat_except_par_get_index(data_mat_train_mat_lst_meanpooled3x3, 1:5, shape = dim(train_mat_lst_meanpooled3x3[[1]]))
print_dataset_datamat_except_par_get_index(data_mat_train_mat_lst_meanpooled4x4, 1:5, shape = dim(train_mat_lst_meanpooled4x4[[1]]))

par(mfcol=c(5,7))
par(mar=c(0, 0, 3, 0), xaxs='i', yaxs='i')
print_dataset_datamat_except_par_get_index(data_mat_test_mat_lst, 1:5, shape = dim(test_mat_lst[[1]]))
print_dataset_datamat_except_par_get_index(data_mat_test_mat_lst_maxpooled2x2, 1:5, shape = dim(test_mat_lst_maxpooled2x2[[1]]))
print_dataset_datamat_except_par_get_index(data_mat_test_mat_lst_maxpooled3x3, 1:5, shape = dim(test_mat_lst_maxpooled3x3[[1]]))
print_dataset_datamat_except_par_get_index(data_mat_test_mat_lst_maxpooled4x4, 1:5, shape = dim(test_mat_lst_maxpooled4x4[[1]]))
print_dataset_datamat_except_par_get_index(data_mat_test_mat_lst_meanpooled2x2, 1:5, shape = dim(test_mat_lst_meanpooled2x2[[1]]))
print_dataset_datamat_except_par_get_index(data_mat_test_mat_lst_meanpooled3x3, 1:5, shape = dim(test_mat_lst_meanpooled3x3[[1]]))
print_dataset_datamat_except_par_get_index(data_mat_test_mat_lst_meanpooled4x4, 1:5, shape = dim(test_mat_lst_meanpooled4x4[[1]]))


par(mfcol=c(5,7))
par(mar=c(0, 0, 3, 0), xaxs='i', yaxs='i')
print_dataset_datamat_except_par_get_index(data_mat_recovered_train_mat_lst, 1:5, shape = dim(train_mat_lst[[1]]))
print_dataset_datamat_except_par_get_index(data_mat_recovered_train_mat_lst_maxpooled2x2, 1:5, shape = dim(train_mat_lst_maxpooled2x2[[1]]))
print_dataset_datamat_except_par_get_index(data_mat_recovered_train_mat_lst_maxpooled3x3, 1:5, shape = dim(train_mat_lst_maxpooled3x3[[1]]))
print_dataset_datamat_except_par_get_index(data_mat_recovered_train_mat_lst_maxpooled4x4, 1:5, shape = dim(train_mat_lst_maxpooled4x4[[1]]))
print_dataset_datamat_except_par_get_index(data_mat_recovered_train_mat_lst_meanpooled2x2, 1:5, shape = dim(train_mat_lst_meanpooled2x2[[1]]))
print_dataset_datamat_except_par_get_index(data_mat_recovered_train_mat_lst_meanpooled3x3, 1:5, shape = dim(train_mat_lst_meanpooled3x3[[1]]))
print_dataset_datamat_except_par_get_index(data_mat_recovered_train_mat_lst_meanpooled4x4, 1:5, shape = dim(train_mat_lst_meanpooled4x4[[1]]))


par(mfcol=c(5,7))
par(mar=c(0, 0, 3, 0), xaxs='i', yaxs='i')
print_dataset_datamat_except_par_get_index(data_mat_recovered_test_mat_lst, 1:5, shape = dim(test_mat_lst[[1]]))
print_dataset_datamat_except_par_get_index(data_mat_recovered_test_mat_lst_maxpooled2x2, 1:5, shape = dim(test_mat_lst_maxpooled2x2[[1]]))
print_dataset_datamat_except_par_get_index(data_mat_recovered_test_mat_lst_maxpooled3x3, 1:5, shape = dim(test_mat_lst_maxpooled3x3[[1]]))
print_dataset_datamat_except_par_get_index(data_mat_recovered_test_mat_lst_maxpooled4x4, 1:5, shape = dim(test_mat_lst_maxpooled4x4[[1]]))
print_dataset_datamat_except_par_get_index(data_mat_recovered_test_mat_lst_meanpooled2x2, 1:5, shape = dim(test_mat_lst_meanpooled2x2[[1]]))
print_dataset_datamat_except_par_get_index(data_mat_recovered_test_mat_lst_meanpooled3x3, 1:5, shape = dim(test_mat_lst_meanpooled3x3[[1]]))
print_dataset_datamat_except_par_get_index(data_mat_recovered_test_mat_lst_meanpooled4x4, 1:5, shape = dim(test_mat_lst_meanpooled4x4[[1]]))

draw_eigenvalue_graph <- function(PCA_res, title_name = "pure")
{
    eigen_res <- PCA_res[[5]]
    eigen_values <- eigen_res$values
    eigen_lst <- cumsum(eigen_values)/sum(eigen_values)
    idx = which(eigen_lst > 0.9)[[1]] # get first index where eigenvalue sum is 90% of total sum
    eigen_df <- data.frame("eigen_index" = seq_along(eigen_lst), "eigen_cum_val" = eigen_lst)
    eigen_tb <- as_tibble(eigen_df)
    graph <- ggplot(data = eigen_tb, mapping = aes(x = eigen_index, y= eigen_cum_val)) + geom_point() + geom_line() + geom_vline(xintercept = idx, color = "red", linetype = "dotdash", size = 1) + scale_x_continuous() + labs(y = "cumulative percentage of variance") + geom_text(aes(x = idx, y = 0.5, label = str_c("index = ",idx), color = "red"), size = 10) + theme(legend.position = "none") + ggtitle(title_name) + theme(plot.title = element_text(face = "bold", hjust = 0.5, size = 20))
    return(graph)
}

pure_eigen_graph <- draw_eigenvalue_graph(PCA_res_train_mat_lst, "pure")
maxpool2x2_eigen_graph <- draw_eigenvalue_graph(PCA_res_train_mat_lst_maxpooled2x2, "maxpool2x2")
maxpool3x3_eigen_graph <- draw_eigenvalue_graph(PCA_res_train_mat_lst_maxpooled3x3, "maxpool3x3")
maxpool4x4_eigen_graph <- draw_eigenvalue_graph(PCA_res_train_mat_lst_maxpooled4x4, "maxpool4x4")
meanpool2x2_eigen_graph <- draw_eigenvalue_graph(PCA_res_train_mat_lst_meanpooled2x2, "meanpool2x2")
meanpool3x3_eigen_graph <- draw_eigenvalue_graph(PCA_res_train_mat_lst_meanpooled3x3, "meanpool3x3")
meanpool4x4_eigen_graph <- draw_eigenvalue_graph(PCA_res_train_mat_lst_meanpooled4x4, "meanpool4x4")

grid.arrange(pure_eigen_graph, maxpool2x2_eigen_graph, maxpool3x3_eigen_graph, maxpool4x4_eigen_graph,
             meanpool2x2_eigen_graph, meanpool3x3_eigen_graph, meanpool4x4_eigen_graph, ncol = 2)

res2_df <- data.frame("data" = rep(c("pure", "maxpooled2x2", "maxpooled3x3", "maxpooled4x4", "meanpooled2x2", "meanpooled3x3", "meanpooled4x4"),4),
                      "model" = rep(c("SVM", "KNN-1", "KNN-2", "Multinom"), each = 7),
                      "accuracy" = c(0.9817, 0.9795, 0.9574, 0.9082, 0.9841, 0.9766, 0.9605,
                                     0.9734, 0.9654, 0.9267, 0.8533, 0.9732, 0.9626, 0.9364, 
                                     0.9693, 0.9612, 0.9188, 0.8448, 0.9696, 0.9582, 0.9322,
                                     0.9190, 0.9109, 0.8802, 0.8210, 0.9130, 0.8922, 0.8606),
                      "train_time" = c(1283.91, 724.59, 552.25, 442.06, 599.12, 421.59, 317.57,
                                       0, 0, 0, 0, 0, 0, 0,
                                       0, 0, 0, 0, 0, 0, 0,
                                       1951.72, 1074.08, 454.01, 103.76, 735.05, 106.23, 66.57),
                      "test_time" = c(42.36, 24.74, 20.00, 19.33, 21.34, 14.53, 12.61,
                                      101.68, 48.26, 26.21, 14.40, 38.49, 16.61, 11.10,
                                      104.03, 56.16, 29.09, 16.72, 42.92, 20.90, 11.26,
                                      0.05, 0.04, 0.03, 0.01, 0.03, 0.03, 0.01),
                      "dim_of_data" = rep(c(87, 52, 33, 23, 45, 25, 16),4),
                      "model_size" = c(196822, 131129, 98037, 82003, 118061, 83198, 68395,
                                       0, 0, 0, 0, 0, 0, 0,
                                       0, 0, 0, 0, 0, 0, 0,
                                       148662, 96285, 67831, 52828, 85831, 55904, 42405)
                      
                     )
res2_tb <- as_tibble(res2_df)

title_size <- 20
text_size <- 20

ggplot(data = res2_tb, aes(x = fct_inorder(data), y = accuracy)) +  geom_bar(aes(fill = fct_inorder(model)), stat = 'identity', position = "dodge2") +labs(x = "data",y = "accuracy", fill = "model") + ggtitle("accuracy of model with data") + theme(plot.title = element_text(face = "bold", hjust = 0.5, size = 20)) + scale_fill_brewer(palette="Set3") + coord_cartesian(ylim = c(0.8, 1.0)) + scale_y_continuous(breaks = seq(0.8,1.0,0.01))

ggplot(data = res2_tb, aes(x = fct_inorder(model), y = accuracy)) +  geom_bar(aes(fill = fct_inorder(data)), stat = 'identity', position = "dodge2") +labs(x = "model",y = "accuracy", fill = "data") + ggtitle("accuracy of model with data") + theme(plot.title = element_text(face = "bold", hjust = 0.5, size = title_size)) + scale_fill_brewer(palette="Set3") + coord_cartesian(ylim = c(0.8, 1.0)) + scale_y_continuous(breaks = seq(0.8,1.0,0.01)) + theme(axis.text=element_text(size=text_size), legend.title = element_text(size = text_size),legend.text = element_text(size = text_size), axis.title = element_text(size=text_size))

ggplot(data = res2_tb, aes(x = fct_inorder(model), y = train_time)) +  geom_bar(aes(fill = fct_inorder(data)), stat = 'identity', position = "dodge2") +labs(x = "model",y = "train time (sec)", fill = "data") + ggtitle("train time of model with data") + theme(plot.title = element_text(face = "bold", hjust = 0.5, size = title_size)) + scale_fill_brewer(palette="Set3")  + theme(axis.text=element_text(size=text_size), legend.title = element_text(size = text_size),legend.text = element_text(size = text_size), axis.title = element_text(size=text_size))

ggplot(data = res2_tb, aes(x = fct_inorder(model), y = test_time)) +  geom_bar(aes(fill = fct_inorder(data)), stat = 'identity', position = "dodge2") +labs(x = "model",y = "test time (sec)", fill = "data") + ggtitle("test time of model with data") + theme(plot.title = element_text(face = "bold", hjust = 0.5, size = title_size)) + scale_fill_brewer(palette="Set3")  + theme(axis.text=element_text(size=text_size), legend.title = element_text(size = text_size),legend.text = element_text(size = text_size), axis.title = element_text(size=text_size))

ggplot(data = res2_tb, aes(x = fct_inorder(model), y = model_size)) +  geom_bar(aes(fill = fct_inorder(data)), stat = 'identity', position = "dodge2") +labs(x = "model",y = "model size (KB)", fill = "data") + ggtitle("model size with data") + theme(plot.title = element_text(face = "bold", hjust = 0.5, size = title_size)) + scale_fill_brewer(palette="Set3")  + theme(axis.text=element_text(size=text_size), legend.title = element_text(size = text_size),legend.text = element_text(size = text_size), axis.title = element_text(size=text_size))

svm_tb <- res2_tb %>% filter(model == "SVM")
knn_1_tb <- res2_tb %>% filter(model == "KNN-1")
knn_2_tb <- res2_tb %>% filter(model == "KNN-2")
multinom_tb <- res2_tb %>% filter(model == "Multinom")

svm_train_graph <- ggplot(data = svm_tb, aes(x = dim_of_data, y = train_time)) + geom_smooth(method = "lm", se=F) + geom_point() + labs(x = "data dimension",y = "train time (sec)") + ggtitle("SVM model train_time vs dimention of data") + theme(plot.title = element_text(face = "bold", hjust = 0.5, size = title_size)) + theme(axis.text=element_text(size=text_size), legend.title = element_text(size = text_size),legend.text = element_text(size = text_size), axis.title = element_text(size=text_size))



multinom_train_graph <- ggplot(data = multinom_tb, aes(x = dim_of_data, y = train_time)) + geom_smooth(method = "lm", se=F) + geom_point() + labs(x = "data dimension",y = "train time (sec)") + ggtitle("Multinom model train_time vs dimention of data") + theme(plot.title = element_text(face = "bold", hjust = 0.5, size = title_size)) + theme(axis.text=element_text(size=text_size), legend.title = element_text(size = text_size),legend.text = element_text(size = text_size), axis.title = element_text(size=text_size))

grid.arrange(svm_train_graph, multinom_train_graph, ncol = 2)

svm_test_graph <- ggplot(data = svm_tb, aes(x = dim_of_data, y = test_time)) + geom_smooth(method = "lm", se=F) + geom_point() + labs(x = "data dimension",y = "test time (sec)") + ggtitle("SVM model test_time vs dimention of data") + theme(plot.title = element_text(face = "bold", hjust = 0.5, size = title_size)) + theme(axis.text=element_text(size=text_size), legend.title = element_text(size = text_size),legend.text = element_text(size = text_size), axis.title = element_text(size=text_size))

knn_1_test_graph <- ggplot(data = knn_1_tb, aes(x = dim_of_data, y = test_time)) + geom_smooth(method = "lm", se=F) + geom_point() + labs(x = "data dimension",y = "test time (sec)") + ggtitle("KNN-1 model test_time vs dimention of data") + theme(plot.title = element_text(face = "bold", hjust = 0.5, size = title_size)) + theme(axis.text=element_text(size=text_size), legend.title = element_text(size = text_size),legend.text = element_text(size = text_size), axis.title = element_text(size=text_size))

knn_2_test_graph <- ggplot(data = knn_2_tb, aes(x = dim_of_data, y = test_time)) + geom_smooth(method = "lm", se=F) + geom_point() + labs(x = "data dimension",y = "test time (sec)") + ggtitle("KNN-2 model test_time vs dimention of data") + theme(plot.title = element_text(face = "bold", hjust = 0.5, size = title_size)) + theme(axis.text=element_text(size=text_size), legend.title = element_text(size = text_size),legend.text = element_text(size = text_size), axis.title = element_text(size=text_size))

grid.arrange(svm_test_graph, knn_1_test_graph, knn_2_test_graph,ncol = 3)


svm_memory_graph <- ggplot(data = svm_tb, aes(x = dim_of_data, y = model_size)) + geom_smooth(method = "lm", se=F) + geom_point() + labs(x = "data dimension",y = "model size (KB)") + ggtitle("SVM model size vs dimention of data") + theme(plot.title = element_text(face = "bold", hjust = 0.5, size = title_size)) + theme(axis.text=element_text(size=text_size), legend.title = element_text(size = text_size),legend.text = element_text(size = text_size), axis.title = element_text(size=text_size))

multinom_memory_graph <- ggplot(data = multinom_tb, aes(x = dim_of_data, y = model_size)) + geom_smooth(method = "lm", se=F) + geom_point() + labs(x = "data dimension",y = "model size (KB)") + ggtitle("Multinom model size vs dimention of data") + theme(plot.title = element_text(face = "bold", hjust = 0.5, size = title_size)) + theme(axis.text=element_text(size=text_size), legend.title = element_text(size = text_size),legend.text = element_text(size = text_size), axis.title = element_text(size=text_size))

grid.arrange(svm_memory_graph, multinom_memory_graph,ncol = 2)

ggplot(data = res2_tb, aes(x = fct_inorder(model), y = model_size)) +  geom_bar(aes(fill = fct_inorder(data)), stat = 'identity', position = "dodge2") +labs(x = "model",y = "model size (KB)", fill = "data") + ggtitle("model size with data") + theme(plot.title = element_text(face = "bold", hjust = 0.5, size = title_size)) + scale_fill_brewer(palette="Set3")  + theme(axis.text=element_text(size=text_size), legend.title = element_text(size = text_size),legend.text = element_text(size = text_size), axis.title = element_text(size=text_size))
```

